version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: pylint
    versions:
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: sqlalchemy
    versions:
    - 1.4.11
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.8
    - 1.4.9
  - dependency-name: mirth-client
    versions:
    - 0.4.1
  - dependency-name: fastapi-auth0
    versions:
    - 0.2.0
  - dependency-name: pytest
    versions:
    - 6.2.3
  - dependency-name: fastapi-pagination
    versions:
    - 0.7.0
  - dependency-name: fakeredis
    versions:
    - 1.5.0
