fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black
        language_version: python3.9
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        language_version: python3.9
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: poetry run tox
        pass_filenames: false
        language: system
