name: Build Client Libraries and Documentation

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # test:
  #   name: Run tests

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1

  #     - uses: harmon758/postgresql-action@v1
  #       with:
  #         postgresql version: "13"

  #     - name: Set up Python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: "3.10"

  #     - name: Install and configure Poetry
  #       uses: snok/install-poetry@v1

  #     - name: Install Dependencies
  #       run: poetry install

  #     - name: Run Tox
  #       run: poetry run tox

  build-spec:
    name: Build OpenAPI spec

    runs-on: ubuntu-latest
    #needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Generate API Spec
        run: poetry run python clients/generate_spec.py

      - name: Store API specification
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: clients/openapi.json

  build-redoc:
    name: Build Redoc documentation

    runs-on: ubuntu-latest
    needs: build-spec

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v3
        with:
          name: openapi-spec
          path: clients/

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - name: Build Redoc documentation
        run: npx redoc-cli build clients/openapi.json --output docs/redoc/index.html

      - name: Store Redoc documentation
        uses: actions/upload-artifact@v3
        with:
          name: redoc-docs
          path: docs/redoc

  build-axios-client:
    name: Build Axios client

    runs-on: ubuntu-latest
    needs: build-spec

    env:
      SNAPSHOT: ${{ github.event_name != 'release' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v3
        with:
          name: openapi-spec
          path: clients/

      - name: Generate Axios Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          config-file: clients/typescript-axios-client/config.json
          openapi-file: clients/openapi.json
          command-args: --additional-properties=snapshot=${SNAPSHOT}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true
          registry-url: "https://registry.npmjs.org"

      - name: Install Axios Client
        working-directory: typescript-axios-client
        run: npm install

      - name: Publish Axios client
        working-directory: typescript-axios-client
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build client documentation
        working-directory: typescript-axios-client
        run: npx typedoc ./index.ts --out ../docs/typescript-axios-client

      - name: Store typescript-axios-client documentation
        uses: actions/upload-artifact@v3
        with:
          name: typescript-axios-client-docs
          path: docs/typescript-axios-client

  publish-docs:
    name: Publish client documentation
    runs-on: ubuntu-latest
    needs: [build-spec, build-redoc, build-axios-client]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v3
        with:
          name: openapi-spec
          path: docs/

      - name: Download Redoc documentation
        uses: actions/download-artifact@v3
        with:
          name: redoc-docs
          path: docs/redoc/

      - name: Download typescript-axios-client documentation
        uses: actions/download-artifact@v3
        with:
          name: typescript-axios-client-docs
          path: docs/typescript-axios-client/

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
