name: Build Client Libraries

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "13"

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.8

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: poetry run tox

  build-spec:
    name: Build OpenAPI spec

    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.8

      - name: Install Dependencies
        run: poetry install
      
      - name: Generate API Spec
        run: poetry run python clients/generate_spec.py

      - name: Store API specification
        uses: actions/upload-artifact@v3
        with:
          name: openapi-spec
          path: clients/openapi.json

  axios-client:
    name: Build Axios client

    runs-on: ubuntu-latest
    needs: build-spec

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v3
        with:
          name: openapi-spec
          path: clients/

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: clients/ukrdc-axios-client
        run: npm install

      - name: Build Axios client
        working-directory: clients/ukrdc-axios-client
        run: npm run generate-client

      - name: Re-version prereleases
        # Only re-version with the commit hash if not triggered by a tag/release
        if: github.event_name == 'workflow_dispatch'
        working-directory: clients/ukrdc-axios-client
        run: npm version "$(npm pkg get version | sed 's/[",]//g')-$(git rev-parse --short "$GITHUB_SHA")"

      - name: Publish Axios client
        working-directory: clients/ukrdc-axios-client
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
