name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Image tag"
        default: "staging"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/renalreg/ukrdc-fastapi:${{github.event.inputs.tags}}
