name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      deployment_env:
        description: "Deployment environment"
        default: "staging"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Install Dependencies
        run: poetry install

      - name: Run Tox
        run: poetry run tox

  publish:
    runs-on: ubuntu-latest
    needs: test

    environment: ${{github.event.inputs.deployment_env}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            GITHUB_SHA=${{ github.sha }}
            GITHUB_REF=${{ github.ref }}
          tags: ghcr.io/renalreg/ukrdc-fastapi:${{github.event.inputs.deployment_env}}
