name: Publish Docker image

on:
  workflow_dispatch:
    inputs:
      deployment_env:
        description: "Deployment environment"
        default: "dev"

jobs:
  publish:
    runs-on: ubuntu-latest

    environment: ${{github.event.inputs.deployment_env}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/renalreg/ukrdc-fastapi:${{github.event.inputs.deployment_env}}
